# Generated by Django 2.2.7 on 2019-11-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
